version: '3'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      # proxies in the build
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: "python3.10"
    volumes:
      - ../:/app/workdir
      # proxies with launched containers
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    tty: true # keep launching containers
